### ISSUE TITLE
ffmpeg: Include Audio Codec 

### ISSUE THREAD

**Issue by iq-404** [bennischober/MetaDataScraper#1]
Hi Benni,
it would be nice to read out the Audio Codec directly.

greetz

david

**Comment by bennischober** [comment]
Hey @iq-404, thanks for the suggestion!
Unfortunately I currently don't have the time to implement new features because of my bachelor thesis and the upcoming exam period.
I still have many ideas for this tool and will add this suggestion to my todo list.

Greetings
Benni

**Comment by bennischober** [comment]
Added in commit 596d9b5b8245f1417001c2600b6b785c8e4a445d

**Comment by chapmanjacobd** [comment]
@iq-404 I made something similar which might provide you with the data that you want:

https://github.com/chapmanjacobd/lb/#start----local-media

```
library fsadd --audio "my music.db" ./audio_folder/
```
